version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Prettier
          command: yarn prettier -l '**/*.{ts,tsx}'
        
      - run: 
          name: Run client tests
          command: yarn test
          working_directory: client/

      - run: 
          name: Run server tests
          command: yarn test
          working_directory: server/